baseURL = "http://example.org/"
languageCode = "en-us"
title = "Maria Lujan Navarro"
theme = "terrassa"
paginate = 3



[params.cta] # Call To Action 
    show = true
    cta = "Contact"
    link = "contact" # Relative URL



[params.separator] # Separators between sections on the home page
    show = false

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.form] # Contact form
    netlify = true
    action = "https://formspree.io/your@email.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Write something"
    inputMsgLength = 750
    inputSubmitValue = "Send"
    [params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"



[params.contact] # Contact info
    email = "lujannavarro26@gmail.com"
    phone = "3330338620"
    skype = "lujan_navarro"
    

[params.social]
    twitter = "https://twitter.com/luchanworld"
    facebook = "https://www.facebook.com/marialujan.navarro.39/"
    github = "https://github.com/LujanWorld"
    codepen = "https://codepen.io/Luzall"
    instagram = "https://www.instagram.com/Luchanworld/"
    youtube = "https://www.youtube.com/channel/UCNAdGZDRYSLPPtKS9KZNYdA?view_as=subscriber"
    linkedin = "https://www.linkedin.com/in/lujan-navarro/"

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
